### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [indigofeather/ama#1]
Screenshot please. I ask everyone this as it can tell a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by indigofeather** [comment]
![2015-07-12 21 37 23](https://cloud.githubusercontent.com/assets/512821/8638022/6b861b78-28de-11e5-8bac-a3bdcd893990.png)

**Comment by sindresorhus** [comment]
Fyi, you close the issue when you've answered it ;)

https://github.com/sindresorhus/amas/blob/master/create-ama.md

**Comment by indigofeather** [comment]
OK :smile:
