### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [indigofeather/ama#3]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by indigofeather** [comment]
My development environment:
- OS: Ubuntu
- Editors: PHPStorm, Atom
- [Laima](https://github.com/IEMustDie/Laima) for Front-end developing.

For the fonts, I love Noto [思源黑體 (Sans CJK)](https://www.google.com/get/noto/help/cjk/).
